version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "time"
    rebase-strategy: "auto"
    schedule:
      interval: "weekly"
      day: "sunday"
    versioning-strategy: "auto"
